AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple express application
Globals:
  Function:
    Timeout: 10
    MemorySize: 1024
    Runtime: nodejs14.x
    Environment:
      Variables:
        DB_USER:
          Ref: DBUser
        DB_PASS:
          Ref: DBPass
        DB_NAME:
          Ref: DBName
        DB_ENV:
          Ref: DBEnv
        CLOUD_SQL_CONNECTION_NAME:
          Ref: CloudSQLConnectionName
        ONET_BASEURL:
          Ref: OnetBaseURL
        ONET_USERNAME:
          Ref: OnetUsername
        ONET_PASSWORD:
          Ref: OnetPassword
        CAREER_ONESTOP_BASEURL:
          Ref: CareerOnestopBaseURL
        CAREER_ONESTOP_USERID:
          Ref: CareerOnestopUserID
        CAREER_ONESTOP_AUTH_TOKEN:
          Ref: CareerOnestopAuthToken
        BASE_URL:
          Ref: BaseURL
        SPACE_ID:
          Ref: SpaceID
        DELIVERY_API:
          Ref: DeliveryAPI
        NODE_OPTIONS:
          Ref: NodeOptions
Resources:
  ExpressBackend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://d4ad-prod/8e8f7f701061cacc4baeb1fb87c657be
      Handler: src/server.handler
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: any
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      SamResourceId: ExpressBackend
Parameters:
  DBUser:
    Type: String
    Description: Database User
  DBPass:
    Type: String
    Description: Database Password
    NoEcho: true
  DBName:
    Type: String
    Description: Database Name
  DBEnv:
    Type: String
    Description: Database Environment
  CloudSQLConnectionName:
    Type: String
    Description: Cloud SQL Connection Name
  OnetBaseURL:
    Type: String
    Description: Onet Base URL
  OnetUsername:
    Type: String
    Description: Onet Username
  OnetPassword:
    Type: String
    Description: Onet Password
    NoEcho: true
  CareerOnestopBaseURL:
    Type: String
    Description: Career Onestop Base URL
  CareerOnestopUserID:
    Type: String
    Description: Career Onestop User ID
  CareerOnestopAuthToken:
    Type: String
    Description: Career Onestop Auth Token
    NoEcho: true
  BaseURL:
    Type: String
    Description: Base URL
  SpaceID:
    Type: String
    Description: Space ID
  DeliveryAPI:
    Type: String
    Description: Delivery API
  NodeOptions:
    Type: String
    Description: Node Options
