version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $DEV_EC2_SSH_FINGERPRINT
      - run:
          name: SSH into EC2
          command: ssh -o StrictHostKeyChecking=no $DEV_EC2_SSH_HOST << EOF
                    cd /home/ubuntu/d4ad
                    git pull
                  EOF 

workflows:
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleCI_Migration