version: 2.1
jobs:
  build-and-test:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:18.16.1-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v3-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-deps-v3-{{ .Branch }}
            - node-deps-v3
      - run:
          name: Install Node.js dependencies
          command: npm ci
      - save_cache:
          key: node-deps-v3-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Node.js tests
          command: npm test
      - run:
          name: Execute feature tests script
          command: DB_ENV=$DB_ENV scripts/feature-tests.sh > feature-test-output.txt
          no_output_timeout: 30m
      - store_artifacts:
          path: feature-test-output.txt
      - store_artifacts:
          path: wiremock.log
      - store_artifacts:
          path: /home/circleci/.npm/_logs/*.log
      - store_artifacts:
          path: ~/project/frontend/cypress/videos
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build-test-deploy:
    jobs:
      - build-and-test