version: 2.1
jobs:
  deploy:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:18.16.1-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - $DEV_EC2_SSH_FINGERPRINT
      - run:
          name: SSH into EC2
          command: ssh -o StrictHostKeyChecking=no $DEV_EC2_SSH_HOST
      - run:
          name: verifying SSH with pull
          command: cd /home/ubuntu/d4ad
      - run:
          name: verifying SSH with pull
          command: cd /home/ubuntu/d4ad

workflows:
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleCI_Migration